theme: minima
url: "https://blogs.fruitiot.com"

plugins:
- jekyll-feed
- jekyll-sitemap

giscus:
  repo: "hanlins/hanlins.github.io"
  repo-id: "MDEwOlJlcG9zaXRvcnkxOTM0MDMxMTU="
  category: "Comments"
  category-id: "DIC_kwDOC4cY684CAmgw"
  mapping: "pathname"
  reaction-enabled: "1"
  theme: "dark_dimmed"
  lang: "en"
  crossorigin: "anonymous"

google_analytics: "G-EYCVQ0N6FY"

defaults:
- scope:
    path: "_posts"
  values:
    layout: "post"
    permalink: "/:year/:title.html"
- scope:
    path: "_drafts"
  values:
    layout: "post"
    permalink: "/:year/:title.html"
